spring:
  config:
    import:
      - optional:configserver:https://ecommerce-config-service.onrender.com
      - optional:file:.env[.properties]
  application:
    name: customer-service
  profiles:
    active: dev
